"""add books categories

Revision ID: 6104d693c4b9
Revises: 8aa373ab937d
Create Date: 2026-03-24 17:11:38.747819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6104d693c4b9'
down_revision: Union[str, Sequence[str], None] = '8aa373ab937d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_book_categories_id'), 'book_categories', ['id'], unique=False)
    op.add_column('books', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'book_categories', ['category_id'], ['id'])
    op.drop_column('books', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'category_id')
    op.drop_index(op.f('ix_book_categories_id'), table_name='book_categories')
    op.drop_table('book_categories')
    # ### end Alembic commands ###
